version: '3'
services:
  db:
    image: postgres:latest
    container_name: my-postgres
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5435:5432"

  webserver:
    image: nginx:latest
    container_name: my-nginx
    ports:
      - "8000:80"
    depends_on:
      - db
